Vagrant.configure(2) do |config|
  config.vm.define 'all_in_one' do |all_in_one|
    all_in_one.vm.box = 'ubuntu/trusty64'
    all_in_one.vm.hostname = 'tsung-all-in-one'

    all_in_one.vm.provider :virtualbox do |vm|
      vm.name = 'tsung-all-in-one'
      vm.memory = 1024
      vm.cpus = 1
    end

    all_in_one.vm.network :forwarded_port, guest: 22, host: 2230, id: 'ssh'
    all_in_one.vm.network 'private_network', ip: '192.168.1.10'

    all_in_one.vm.provision 'ansible' do |ansible|
      ansible.limit = 'all'
      ansible.inventory_path = 'playbooks/machines.vagrant'
      ansible.playbook = 'playbooks/vagrant-all-in-one.yml'
    end
  end
end
