---
- hosts: injectors
  sudo: True
  roles:
    - hosts
    - resolv
    - locale
    - common-tools
    - erlang
    - munin-node

- hosts: controller
  roles:
    - hosts
    - resolv
    - locale
    - common-tools
    - erlang
    - munin
    - munin-node
