# TODO: Add file with node variables here.

- hosts: injectors
  sudo: True
  roles:
    - hosts
    - resolv
    - locale
    - common-tools
    - erlang
    - munin-node
    - tsung

- hosts: controller
  roles:
    - hosts
    - resolv
    - locale
    - common-tools
    - erlang
    - munin
    - munin-node
    - tsung
    - tsung_scenario
    - tsung_reports
