---
- hosts: all
  sudo: True

  vars:
    - controller_munin: ^192\.168\.1\.10$

    - controller: { "private_ip_address": 192.168.1.10, "private_dns_name": "controller.localdomain", "private_short_name": "controller" }
    - injectors:
      - { "private_ip_address": 192.168.1.10, "private_dns_name": "injector1.localdomain", "private_short_name": "injector1" }

  roles:
    - hosts
    - resolv
    - locale
    - common-tools
    - erlang
    - munin
    - munin-node
