Vagrant.configure(2) do |config|
  config.vm.define 'vm-node-env' do |node_env|
    node_env.vm.box = 'bento/centos-6.7'

    node_env.vm.provider :virtualbox do |vm|
      vm.name = 'vm-node-env'

      vm.memory = 2048
      vm.cpus = 1
    end

    node_env.vm.network :forwarded_port, guest: 22, host: 2200, id: 'ssh'
    node_env.vm.network 'private_network', ip: '192.168.1.10'

    node_env.vm.provision 'ansible' do |ansible|
      ansible.limit = 'all'
      ansible.inventory_path = 'provisioning/machines.vagrant'
      ansible.playbook = 'provisioning/nodejs-environment.yml'
    end
  end
end
