- name: clients.xml
  template:
    src=./roles/tsung_scenario/templates/clients.xml.j2
    dest=/home/{{ tsung_user_name }}/clients.xml
    owner={{ tsung_user_name }}
    group={{ tsung_user_name }}
    mode=0644

- name: options.xml
  template:
    src=./roles/tsung_scenario/templates/options.xml.j2
    dest=/home/{{ tsung_user_name }}/options.xml
    owner={{ tsung_user_name }}
    group={{ tsung_user_name }}
    mode=0644

- name: run.xml
  template:
    src=./roles/tsung_scenario/templates/run.xml.j2
    dest=/home/{{ tsung_user_name }}/run.xml
    owner={{ tsung_user_name }}
    group={{ tsung_user_name }}
    mode=0644