Vagrant.configure(2) do |config|
  config.vm.define 'vector' do |vector|
    vector.vm.box = 'ubuntu/wily64'

    vector.vm.provider :virtualbox do |vm|
      vm.memory = 1024
      vm.cpus = 1
    end

    vector.vm.network :forwarded_port, guest: 22, host: 2230, id: 'ssh'
    vector.vm.network 'private_network', ip: '192.168.1.10'

    vector.vm.provision 'ansible' do |ansible|
      ansible.limit = 'all'
      ansible.inventory_path = 'playbooks/machines.vagrant'
      ansible.playbook = 'playbooks/vector.yml'
    end
  end
end
