Vagrant.configure('2') do |config|
  config.vm.box = 'chef/centos-6.5'

  config.vm.provider 'virtualbox' do |machine|
    machine.name = 'vm-mongodb-rabbitmq'
    machine.cpus = 1
    machine.memory = 1024
  end

  config.vm.network 'public_network'

  config.vm.provision 'shell', path: 'utils.sh'
  config.vm.provision 'shell', path: 'rabbitmq.sh'
  config.vm.provision 'shell', path: 'mongodb.sh'
end