Vagrant.configure(2) do |config|
  config.vm.box = 'hashicorp/precise64'

  config.vm.provider :virtualbox do |vm|
    vm.name = 'erlang-elixir'

    vm.memory = 512
    vm.cpus = 1

    vm.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vm.customize ['modifyvm', :id, '--ioapic', 'on']
  end

  config.vm.hostname = 'erlang-elixir'

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'provisioning/playbook.yml'
    ansible.inventory_path = 'provisioning/inventory'

    ansible.sudo = true
  end
end
