Vagrant.configure(2) do |config|
  config.vm.box = 'centos/7'

  config.vm.provider :virtualbox do |vm|
    vm.name = 'hello-world'

    vm.memory = 256
    vm.cpus = 1

    vm.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vm.customize ['modifyvm', :id, '--ioapic', 'on']
  end

  config.vm.hostname = 'hello-world'
  config.vm.network :private_network, ip: '192.168.111.222'

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = 'provisioning/playbook.yml'
    ansible.inventory_path = 'provisioning/inventory'

    ansible.sudo = true
  end
end
